CREATE TABLE IF NOT EXISTS edu_safety_record
(
    id                     BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_module          VARCHAR(50) NOT NULL COMMENT 'source module',
    scene                  VARCHAR(50) NOT NULL COMMENT 'safety scene',
    user_role              VARCHAR(20) NOT NULL COMMENT 'user role',
    grade_level            VARCHAR(20) NOT NULL COMMENT 'grade level',
    user_id                BIGINT COMMENT 'user id',
    class_id               BIGINT COMMENT 'class id',
    course_id              BIGINT COMMENT 'course id',
    chapter_id             BIGINT COMMENT 'chapter id',
    input_text             TEXT COMMENT 'input text',
    output_text            TEXT COMMENT 'output text',
    allowed                TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'allowed',
    risk_level             VARCHAR(20) NOT NULL COMMENT 'risk level',
    risk_types             TEXT COMMENT 'risk types json',
    decision               VARCHAR(20) NOT NULL COMMENT 'decision',
    reason                 TEXT COMMENT 'reason',
    suggestion             TEXT COMMENT 'suggestion',
    processed_text         TEXT COMMENT 'processed text',
    evidence_level         VARCHAR(20) COMMENT 'RAG evidence level',
    evidence_score         DOUBLE COMMENT 'RAG evidence score',
    manual_review_required TINYINT(1) DEFAULT 0 COMMENT 'manual review required',
    review_status          VARCHAR(20) DEFAULT 'NOT_REQUIRED' COMMENT 'review status',
    review_by              BIGINT COMMENT 'review user id',
    review_by_name         VARCHAR(50) COMMENT 'review user name',
    review_time            DATETIME COMMENT 'review time',
    review_comment         TEXT COMMENT 'review comment',
    metadata_json          TEXT COMMENT 'request metadata json',
    debug_json             TEXT COMMENT 'debug info json',
    create_time            DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_create_time (create_time),
    INDEX idx_risk_level (risk_level),
    INDEX idx_source_module (source_module),
    INDEX idx_scene (scene),
    INDEX idx_manual_review_required (manual_review_required)
) COMMENT 'education safety evaluation record';
