edu:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: edu
    username: root
    password: 316030
  redis:
    host: 127.0.0.1
    port: 6379
    #password: root
    database: 6
  minio:
    endpoint: http://192.168.40.128:9000
    access_key: root
    secret_key: rootroot
    bucker_name: edu
    public_base_url: http://localhost:8080
    default_avatar: avatar/default_avatar.png
  # jwt、mail 不用改动，本地自测完全通用
  jwt:
    secret-key: abcdefghijklmnopqabcdefghijklmnopq
    expire-time: 7200000
    jwt-name: Authorization
  mail:
    from-name: Edu-B
    captcha:
      length: 6
      expire-minutes: 5

