edu:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.40.135
    port: 3306
    database: edu
    username: root
    password: root
  redis:
    host: 192.168.40.135
    port: 6379
    #password: root
    database: 6
  minio:
    endpoint: http://192.168.40.135:9000
    access_key: root
    secret_key: rootroot
    bucker_name: edu
    public_base_url: http://localhost:8080
    avatar:
      avatar_files_base_url: avatar/files/
      default_avatar: avatar/default_avatar.png
    rag:
      rag_files_base_url: rag/files/
      max_ref_rag_kb_count: 10
      max_ref_rag_doc_count: 100
  ai-model:
    openai:
      api-key: sk-xxx
      base-url: https://api.deepseek.com
      chat-model:
        model-name: deepseek-v4-flash
        completions-path: null
      embedding-model:
        model-name: qwen-plus
        completions-path: /chat/completions
    alibaba:
      api-key: sk-xxx
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat-model:
        model-name: qwen-plus
        completions-path: /chat/completions
      embedding-model:
        model-name: qwen-plus
        completions-path: /chat/completions

  # jwt、mail 不用改动，本地自测完全通用
  jwt:
    secret-key: abcdefghijklmnopqabcdefghijklmnopq
    expire-time: 7200000
    jwt-name: Authorization
  mail:
    from-name: Edu-B
    captcha:
      length: 6
      expire-minutes: 5

